### ISSUE TITLE
Error: Cannot find module 'fs-plus'

### ISSUE THREAD

**Issue by harobed** [facebooknuclide/atom-in-orbit#10]
```
npm run build

> atom-in-orbit@0.0.0 build /Users/stephane/tests/atom-in-orbit
> node ./scripts/build.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'fs-plus'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/stephane/tests/atom/src/compile-cache.js:9:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/nvm/0.33.0/versions/node/v6.9.2/bin/node" "/usr/local/opt/nvm/versions/node/v6.9.2/bin/npm" "run" "build"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! atom-in-orbit@0.0.0 build: `node ./scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the atom-in-orbit@0.0.0 build script 'node ./scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-in-orbit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-in-orbit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-in-orbit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/stephane/tests/atom-in-orbit/npm-debug.log
```

* yarn executed
* 

```
$ cd ../atom; git log -1
commit f7d3f0210bf6ff1b4193d8a8b8a54c199b561bc2
Author: Nathan Sobo <nathan@github.com>
Date:   Wed Nov 2 21:54:03 2016 -0600

    :arrow_up: atom-keymap

    Fixes atom/atom-keymap#165
```

* 

```
cat config.local.json
{
  "ATOM_SRC": "/Users/stephane/tests/atom"
}
```

*

```
$ node --version
v6.9.2
```

**Comment by AlexanderLuthor** [comment]
Try launching the command `apm install` in atom's source directory, it should install all the needed modules...

**Comment by carlosperate** [comment]
I was having the same issue. I had built and installed Atom from source, and then run `apm install` in the atom source directory, but still the same.

It did seem to go away after doing `npm install` in the atom-in-orbit source directory. Is that a required step missing from the readme?

**Comment by AlexanderLuthor** [comment]
So it seems, I did the same (using yarn)
These are the steps I've donem and they've worked: https://github.com/facebooknuclide/atom-in-orbit/issues/5#issuecomment-269873905
