### ISSUE TITLE
Error: spawnSync patch ENOENT

### ISSUE THREAD

**Issue by engineer135** [facebooknuclide/atom-in-orbit#11]
> npm run build

> atom-in-orbit@0.0.0 build D:\dev\atom-in-orbit
> node ./scripts/build.js

child_process.js:513
    throw err;
    ^

Error: spawnSync patch ENOENT
    at exports._errnoException (util.js:1022:11)
    at spawnSync (child_process.js:468:20)
    at execFileSync (child_process.js:505:13)
    at Object.<anonymous> (D:\dev\atom-in-orbit\scripts\build.js:50:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.j
s" "run" "build"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! atom-in-orbit@0.0.0 build: `node ./scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the atom-in-orbit@0.0.0 build script 'node ./scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-in-orbit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-in-orbit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-in-orbit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

and my config.local.json file
{
  "ATOM_SRC": "D:/dev/atom"
}

What shoud I do?

**Comment by OptimisticPeach** [comment]
I have the same problem too. Win10, node 6.11.3, npm 3.10.10, and I am using version 089fa92117f5d0ead54b56ee208a2baa24d9c4e2 of atom master.
