### ISSUE TITLE
Build on my system: node ./scripts/build.js

### ISSUE THREAD

**Issue by akoranne** [facebooknuclide/atom-in-orbit#4]
Hi, 
I attempted to build the atom on my mac and it is error-ing out. 
Below are the command outputs.

```
[~/Workspaces/GitHub/10-tools/atom-in-orbit]
(master)* $> node --version
v7.3.0
```

```
[~/Workspaces/GitHub/10-tools/atom-in-orbit]
(master)* $> npm --version
3.10.10
```

```
[~/Workspaces/GitHub/10-tools/atom-in-orbit]
(master)* $> npm run build

> atom-in-orbit@0.0.0 build /Users/ajaykoranne/Workspaces/GitHub/10-tools/atom-in-orbit
> node ./scripts/build.js

/Users/ajaykoranne/Workspaces/GitHub/10-tools/atom-in-orbit/scripts/config.js:17
    throw e;
    ^

SyntaxError: Unexpected string in JSON at position 66
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/Users/ajaykoranne/Workspaces/GitHub/10-tools/atom-in-orbit/scripts/config.js:12:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ajaykoranne/Workspaces/GitHub/10-tools/atom-in-orbit/scripts/build.js:19:16)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.3.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! atom-in-orbit@0.0.0 build: `node ./scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the atom-in-orbit@0.0.0 build script 'node ./scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-in-orbit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-in-orbit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-in-orbit
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ajaykoranne/Workspaces/GitHub/10-tools/atom-in-orbit/npm-debug.log
```

```
[~/Workspaces/GitHub/10-tools/atom-in-orbit]
(master)* $> cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.3.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v7.3.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle atom-in-orbit@0.0.0~prebuild: atom-in-orbit@0.0.0
6 silly lifecycle atom-in-orbit@0.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle atom-in-orbit@0.0.0~build: atom-in-orbit@0.0.0
8 verbose lifecycle atom-in-orbit@0.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle atom-in-orbit@0.0.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/ajaykoranne/Workspaces/GitHub/10-tools/atom-in-orbit/node_modules/.bin:/usr/local/Cellar/node/7.3.0/bin:/Users/ajaykoranne/.rvm/gems/ruby-2.3.0/bin:/Users/ajaykoranne/.rvm/gems/ruby-2.3.0@global/bin:/Users/ajaykoranne/.rvm/rubies/ruby-2.3.0/bin:/opt/local/share/google-cloud-sdk/bin:.:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/local/sbin:/opt/local/bin:/opt/local/store:/Library/Java/JavaVirtualMachines/jdk1.8.0_72.jdk/Contents/Home/bin:/Applications/Development/maven/bin:/opt/local/gradle/bin:/usr/local/mysql/bin:/usr/local/opt/go/libexec/bin:/Users/ajaykoranne/Workspaces/Go/bin:/usr/local/php5/bin:/Users/ajaykoranne/.rvm/bin
10 verbose lifecycle atom-in-orbit@0.0.0~build: CWD: /Users/ajaykoranne/Workspaces/GitHub/10-tools/atom-in-orbit
11 silly lifecycle atom-in-orbit@0.0.0~build: Args: [ '-c', 'node ./scripts/build.js' ]
12 silly lifecycle atom-in-orbit@0.0.0~build: Returned: code: 1  signal: null
13 info lifecycle atom-in-orbit@0.0.0~build: Failed to exec build script
14 verbose stack Error: atom-in-orbit@0.0.0 build: `node ./scripts/build.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid atom-in-orbit@0.0.0
16 verbose cwd /Users/ajaykoranne/Workspaces/GitHub/10-tools/atom-in-orbit
17 error Darwin 16.3.0
18 error argv "/usr/local/Cellar/node/7.3.0/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v7.3.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error atom-in-orbit@0.0.0 build: `node ./scripts/build.js`
22 error Exit status 1
23 error Failed at the atom-in-orbit@0.0.0 build script 'node ./scripts/build.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the atom-in-orbit package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./scripts/build.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs atom-in-orbit
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls atom-in-orbit
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
[~/Workspaces/GitHub/10-tools/atom-in-orbit]
(master)* $>
```

```
ajaykoranne@Ajays-MacBook-Pro:[~/Workspaces/GitHub/10-tools/atom-in-orbit]
(master)* $> node ./scripts/build.js
/Users/ajaykoranne/Workspaces/GitHub/10-tools/atom-in-orbit/scripts/config.js:17
    throw e;
    ^

SyntaxError: Unexpected string in JSON at position 66
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/Users/ajaykoranne/Workspaces/GitHub/10-tools/atom-in-orbit/scripts/config.js:12:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ajaykoranne/Workspaces/GitHub/10-tools/atom-in-orbit/scripts/build.js:19:16)
```

Please let me know what fixes I need to make

Regards,
--ajay

**Comment by akoranne** [comment]
Never mind. Atom does not build well with node v7

```
/Users/ajaykoranne/Workspaces/GitHub/10-tools/atom/script/lib/verify-machine-requirements.js:23
    throw new Error(`Atom does not build properly on node v7+. node v${fullVersion} is installed.`)
```

I will have to downgrade my node to build atom-in-orbit. I will pass it for now.

**Comment by bolinfest** [comment]
@akoranne FYI, [`nvm`](https://github.com/creationix/nvm) is a handy tool for switching between multiple Node versions.
