### ISSUE TITLE
Can't seem to build on a fresh Ubuntu 16.04 install

### ISSUE THREAD

**Issue by Pitu** [facebooknuclide/atom-in-orbit#5]
I'm getting the following error

```
/var/www/html/atom/atom-in-orbit> npm run build

> atom-in-orbit@0.0.0 build /var/www/html/atom/atom-in-orbit
> node ./scripts/build.js

child_process.js:506
    throw err;
    ^

Error: Command failed: patch /var/www/html/atom/atom/src/atom-environment.coffee /var/www/html/atom/atom-in-orbit/scripts/patches/src/atom-environment.coffee.patch

    at checkExecSyncError (child_process.js:483:13)
    at execFileSync (child_process.js:503:13)
    at Object.<anonymous> (/var/www/html/atom/atom-in-orbit/scripts/build.js:50:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)

npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! atom-in-orbit@0.0.0 build: `node ./scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the atom-in-orbit@0.0.0 build script 'node ./scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-in-orbit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-in-orbit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-in-orbit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/atom/atom-in-orbit/npm-debug.log
```

```
/var/www/html/atom/atom-in-orbit> cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle atom-in-orbit@0.0.0~prebuild: atom-in-orbit@0.0.0
6 silly lifecycle atom-in-orbit@0.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle atom-in-orbit@0.0.0~build: atom-in-orbit@0.0.0
8 verbose lifecycle atom-in-orbit@0.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle atom-in-orbit@0.0.0~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/var/www/html/atom/atom-in-orbit/node_modules/.bin:/home/kana/bin:/home/kana/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle atom-in-orbit@0.0.0~build: CWD: /var/www/html/atom/atom-in-orbit
11 silly lifecycle atom-in-orbit@0.0.0~build: Args: [ '-c', 'node ./scripts/build.js' ]
12 silly lifecycle atom-in-orbit@0.0.0~build: Returned: code: 1  signal: null
13 info lifecycle atom-in-orbit@0.0.0~build: Failed to exec build script
14 verbose stack Error: atom-in-orbit@0.0.0 build: `node ./scripts/build.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid atom-in-orbit@0.0.0
16 verbose cwd /var/www/html/atom/atom-in-orbit
17 error Linux 4.4.0-57-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
19 error node v6.9.2
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error atom-in-orbit@0.0.0 build: `node ./scripts/build.js`
22 error Exit status 1
23 error Failed at the atom-in-orbit@0.0.0 build script 'node ./scripts/build.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the atom-in-orbit package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./scripts/build.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs atom-in-orbit
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls atom-in-orbit
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Using:
`npm` v3.10.9
`node` v6.9.2

**Comment by mwkang** [comment]
I have a same error..
In my server specification.
```
CentOS release 6.3 (Final)
node: 6.9.2
npm: 3.10.9
```

**Comment by qeesung** [comment]
+1 

```
Ubuntu 14.04
node v7.0.0
npm v.3.10.8
```

**Comment by EtherTyper** [comment]
:+1:

```
macOS 10.12.3 Beta (16D17a)
node v7.3.0
npm v4.1.1
```

**Comment by EtherTyper** [comment]
Does anyone know the Atom issue describing this error?

**Comment by rubiconvvv** [comment]
While run patch command
```
patch /home/stan/code/atom/src/atom-environment.coffee /home/stan/Dev/atom-in-orbit/scripts/patches/src/atom-environment.coffee.patch
```
Result
```
Reversed (or previously applied) patch detected!  Assume -R? [n] 
```
It's seems strange because patch applied to fresh version of atom editor

**Comment by AlexanderLuthor** [comment]
It seems a problem during the patching of the code...
Be sure that in config.local.json you're pointing to the specific release of Atom written in the config.json file of atom-in-orbit.
Steps I've done, and they've worked:

- clone the atom repository locally

- move to atom's source folder

- switch to the specified commit 
`git checkout` and the specified `"ATOM_REVISION"`
in my/this case:
`git checkout f7d3f0210bf6ff1b4193d8a8b8a54c199b561bc2`

- move to atom-in-orbit's folder

- point to atom's source folder **with an absolute path** inside the config.local.json file (as specified in the README)

- `yarn`

- `npm run build`

**Comment by deathemperor** [comment]
@AlexanderLuthor did what you suggest, still can't build int on MacOSX 10.12.1

**Comment by bugcy013** [comment]
@AlexanderLuthor  We tried same ubuntu 16.04. have followed  your comment [ #5 (comment) ](https://github.com/facebooknuclide/atom-in-orbit/issues/5#issuecomment-269873905) still I can't build . Please guide me. Note: I have not executed yarn command.

``
➜  atom-in-orbit git:(master) ✗ npm run build

> atom-in-orbit@0.0.0 build /home/dhanasekaran/atom-in-orbit
> node ./scripts/build.js

child_process.js:506
    throw err;
    ^

Error: Command failed: patch /home/dhanasekaran/atom-in-orbit/atom/src/atom-environment.coffee /home/dhanasekaran/atom-in-orbit/scripts/patches/src/atom-environment.coffee.patch

    at checkExecSyncError (child_process.js:483:13)
    at execFileSync (child_process.js:503:13)
    at Object.<anonymous> (/home/dhanasekaran/atom-in-orbit/scripts/build.js:50:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
``

**Comment by AlexanderLuthor** [comment]
It's complaining about an old version of node, so I think you need to update it.
The `yarn` command it's needed for downloading all the required dependencies in the local node_modules folder; it's equivalent to the original `npm install`(yarn is just faster).
Pay attention to the commit to checkout to the right commit (after downloading the source code and placing it to the specified directory)

**Comment by bugcy013** [comment]
@AlexanderLuthor Thanks for your comment, Currently Have changed to node version to latest.

```
root@911a296b13cc:~/atom# node --version
v7.5.0
root@911a296b13cc:~/atom# npm -v
4.1.2
root@911a296b13cc:~/atom# 
```

Still can't build atom-in-orbit on ubuntu system, Have linked build console log and debug log. [atom-in-orbit.build](https://gist.github.com/bugcy013/2afe024971d78103bae583b771a35c81) and  [atom-in-orbit-npm-debug.log](https://gist.github.com/bugcy013/694225eb8b25c6554fdf3ac165c5ef65) 

Please let me know your thoughts.

**Comment by carlosperate** [comment]
Has the patch already been applied, and failing when trying to apply it again?

**Comment by bugcy013** [comment]
Hi @carlosperate 
You are correct, patch already applied, when trying again try to patch it gives exception.

@AlexanderLuthor @carlosperate Finally I can build it's working, thanks for your support.

In my case,  below-mentioned packages have used.

```
root@5079e451cb6d:~# node --version
v6.9.5
root@5079e451cb6d:~# npm -v
3.10.10
```

**Comment by marcoarruda** [comment]
Hi @bugcy013,

What did you do to build it properly?
Because I'm having the same problems, but I didn't understand what you changed to make it work.

See below the error message:
![image](https://user-images.githubusercontent.com/216738/27771258-ce82a11c-5f21-11e7-8b88-35c878d06a27.png)


I'm working with:
Ubuntu 14.04
node v6.9.5
npm 3.10.10
