### ISSUE TITLE
Cannot build on macOS 10.12.2 (16C67)

### ISSUE THREAD

**Issue by rdewolff** [facebooknuclide/atom-in-orbit#6]
Followed the instructions but got the following error :

```
➜  atom-in-orbit git:(master) ✗ npm run build

> atom-in-orbit@0.0.0 build /Users/rdewolff/Project/atom-in-orbit
> node ./scripts/build.js

child_process.js:506
    throw err;
    ^

Error: Command failed: patch /Users/rdewolff/Project/atom/src/atom-environment.coffee /Users/rdewolff/Project/atom-in-orbit/scripts/patches/src/atom-environment.coffee.patch

    at checkExecSyncError (child_process.js:483:13)
    at execFileSync (child_process.js:503:13)
    at Object.<anonymous> (/Users/rdewolff/Project/atom-in-orbit/scripts/build.js:50:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! atom-in-orbit@0.0.0 build: `node ./scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-in-orbit@0.0.0 build script 'node ./scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-in-orbit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-in-orbit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-in-orbit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rdewolff/Project/atom-in-orbit/npm-debug.log
```

Which seems to come from atom build?

**Comment by Pitu** [comment]
Same issue as #5
