### ISSUE TITLE
Build errors Windows 10

### ISSUE THREAD

**Issue by thebetterjort** [facebooknuclide/atom-in-orbit#7]
C:\Users\d7\atom-in-orbit>yarn build
yarn build v0.18.1
$ node ./scripts/build.js
C:\Users\d7\atom-in-orbit\scripts\config.js:17
    throw e;
    ^

SyntaxError: Unexpected token U in JSON at position 21
    at Object.parse (native)
    at Object.<anonymous> (C:\Users\d7\atom-in-orbit\scripts\config.js:12:21)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\d7\atom-in-orbit\scripts\build.js:19:16)
error Command failed with exit code 1.

**Comment by EtherTyper** [comment]
> C:\Users\d7\atom-in-orbit\scripts\config.js:17
> 
> SyntaxError: Unexpected token U in JSON at position 21

At [line 17 of `config.js`](https://github.com/facebooknuclide/atom-in-orbit/blob/master/scripts/config.js#L16) (the inside of the `if` statement):

```js
// If the file does not exist, then that's fine, but if it contains malformed
// JSON, then the user should know.
if (e.code !== 'ENOENT') {
  throw e;
}
```

This is what the [build instructions](https://github.com/facebooknuclide/atom-in-orbit#building-the-webapp) say:

> First, you must create a `config.local.json` file in the root of your project with some configuration information. Specifically, it needs the location of a [source checkout of Atom](https://github.com/atom/atom) that has been built at the revision specified in the `config.json` file.

The error is caused not because of your platform or an incompatibility with Windows 10, but because it cannot parse the `config.local.json` configuration file _you wrote_, stating where you have the Atom source code. Please share the contents of this file, so we can determine where the process erred.

Thanks,
@EtherTyper
